# Generated by Django 4.1.2 on 2022-11-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilemodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='about_user',
            field=models.TextField(blank=True, default=''),
        ),
    ]
