# Generated by Django 4.1.2 on 2022-10-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='DoctorsSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.SmallIntegerField(blank=True, choices=[(1, 'surgeon'), (2, 'nurse'), (3, 'family doctor')])),
            ],
            options={
                'db_table': 'doctors_spec',
            },
        ),
    ]
