# Generated by Django 4.1.2 on 2022-10-24 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('staff', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsModel',
            fields=[
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='doctor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patients', models.ManyToManyField(blank=True, related_name='patients', to='patients.patientsmodel')),
                ('specialization', models.ManyToManyField(blank=True, to='staff.doctorslistofspecializations')),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
    ]
