# Generated by Django 4.1.2 on 2022-10-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsmodel',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='patients', to='patients.patientsmodel'),
        ),
        migrations.AlterField(
            model_name='doctorsmodel',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='staff.doctorsspecialization'),
        ),
    ]
