# Generated by Django 4.1.2 on 2022-10-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_doctorsmodel_patients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsspecialization',
            name='specialization',
            field=models.SmallIntegerField(choices=[(1, 'surgeon'), (2, 'nurse'), (3, 'family doctor')]),
        ),
    ]
