# Generated by Django 4.1.2 on 2022-10-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_doctorsspecialization_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsspecialization',
            name='specialization',
            field=models.CharField(max_length=120),
        ),
    ]
