# Generated by Django 4.1.2 on 2022-10-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_doctorsspecialization_specialization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorsSpecialization',
            new_name='DoctorsListOfSpecializations',
        ),
        migrations.AlterModelTable(
            name='doctorslistofspecializations',
            table='doctors_spec_list',
        ),
    ]
