# Generated by Django 4.1.2 on 2022-10-24 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientsmodel',
            name='patient',
        ),
        migrations.AddField(
            model_name='patientsmodel',
            name='patient_id',
            field=models.OneToOneField(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
