# Generated by Django 4.1.2 on 2022-10-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.SmallIntegerField(choices=[(1, '9:30'), (2, '10:30')])),
                ('appointment_dat', models.DateField(choices=[(1, '9:30'), (2, '10:30')])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
