# Generated by Django 4.1.2 on 2022-10-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=210)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
    ]
