# Generated by Django 4.1.2 on 2022-10-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicmodel',
            name='doctor_list',
            field=models.ManyToManyField(to='staff.doctorsmodel'),
        ),
    ]
