# Generated by Django 4.1.2 on 2022-10-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRoles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroles',
            old_name='patients',
            new_name='roles',
        ),
    ]
